package dev.kaixinguo.standalonecodepractice.ai

import dev.kaixinguo.standalonecodepractice.ui.workspace.ProblemExecutionPipeline
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

class GeneratedProblemDraftJsonParserTest {
    private val parser = GeneratedProblemDraftJsonParser()

    @Test
    fun parse_acceptsShareFileSchema() {
        val parsed = parser.parse(
            """
            {
              "schemaVersion": 1,
              "type": "standalone_code_practice_problem",
              "problem": {
                "title": "Two Sum",
                "difficulty": "Easy",
                "summary": "Generated by qwen as an array problem.",
                "statementMarkdown": "Find two numbers.",
                "exampleInput": "nums = [2,7,11,15]\ntarget = 9",
                "exampleOutput": "[0,1]",
                "starterCode": "class Solution:\n    def twoSum(self, nums, target):\n        pass",
                "hints": ["Use a hash map."],
                "executionPipeline": "single_method"
              }
            }
            """.trimIndent()
        )

        assertEquals("Two Sum", parsed.title)
        assertEquals("Easy", parsed.difficulty)
        assertEquals("Generated by qwen as an array problem.", parsed.summary)
        assertEquals(ProblemExecutionPipeline.SingleMethod, parsed.executionPipeline)
    }

    @Test
    fun parse_acceptsBareProblemObject() {
        val parsed = parser.parse(
            """
            ```json
            {
              "title": "Invert Tree",
              "difficulty": "Easy",
              "summary": "Generated by preview.gguf as a binary tree problem.",
              "statementMarkdown": "Invert the tree.",
              "exampleInput": "root = [4,2,7,1,3,6,9]",
              "exampleOutput": "[4,7,2,9,6,3,1]",
              "starterCode": "",
              "hints": ["Think recursively."]
            }
            ```
            """.trimIndent()
        )

        assertEquals("Invert Tree", parsed.title)
        assertEquals(listOf("Think recursively."), parsed.hints)
        assertNull(parsed.executionPipeline)
    }
}
