package dev.kaixinguo.standalonecodepractice.ui.workspace

import dev.kaixinguo.standalonecodepractice.data.SharedProblemFile
import org.junit.Assert.assertEquals
import org.junit.Test

class ProblemComposerSupportTest {
    @Test
    fun withGeneratedProblem_preservesExistingFieldsWhenAiLeavesThemBlank() {
        val original = ProblemComposerDraft(
            destinationSetId = "set-1",
            title = "Existing Title",
            difficulty = "Medium",
            summary = "Existing summary",
            statementMarkdown = "Existing statement",
            exampleInput = "n = 5",
            exampleOutput = "8",
            starterCode = "class Solution:\n    pass",
            starterCodeMode = ProblemStarterCodeMode.Manual,
            hintsText = "Existing hint",
            submissionTestSuiteJson = "{\n  \"cases\": []\n}",
            executionPipelineOverride = ProblemExecutionPipeline.OperationSequence.storageValue
        )

        val updated = original.withGeneratedProblem(
            SharedProblemFile(
                title = "Generated Title",
                difficulty = "",
                summary = "",
                statementMarkdown = "",
                exampleInput = "",
                exampleOutput = "13",
                starterCode = "",
                hints = emptyList(),
                submissionTestSuite = null,
                executionPipeline = null
            )
        )

        assertEquals("set-1", updated.destinationSetId)
        assertEquals("Generated Title", updated.title)
        assertEquals("Medium", updated.difficulty)
        assertEquals("Existing summary", updated.summary)
        assertEquals("Existing statement", updated.statementMarkdown)
        assertEquals("n = 5", updated.exampleInput)
        assertEquals("13", updated.exampleOutput)
        assertEquals("class Solution:\n    pass", updated.starterCode)
        assertEquals(ProblemStarterCodeMode.Manual, updated.starterCodeMode)
        assertEquals("Existing hint", updated.hintsText)
        assertEquals("{\n  \"cases\": []\n}", updated.submissionTestSuiteJson)
        assertEquals(ProblemExecutionPipeline.OperationSequence.storageValue, updated.executionPipelineOverride)
    }

    @Test
    fun withGeneratedProblem_appliesReturnedFieldsIntoComposerDraft() {
        val original = ProblemComposerDraft(destinationSetId = "set-1")

        val updated = original.withGeneratedProblem(
            SharedProblemFile(
                title = "Sliding Window Maximum",
                difficulty = "Hard",
                summary = "Generated by qwen2.5 as a sliding-window deque problem.",
                statementMarkdown = "Find the maximum in each window.",
                exampleInput = "nums = [1,3,-1,-3,5,3,6,7]\nk = 3",
                exampleOutput = "[3,3,5,5,6,7]",
                starterCode = "class Solution:\n    def maxSlidingWindow(self, nums, k):\n        pass",
                hints = listOf("Use a deque."),
                submissionTestSuite = null,
                executionPipeline = ProblemExecutionPipeline.SingleMethod
            )
        )

        assertEquals("set-1", updated.destinationSetId)
        assertEquals("Sliding Window Maximum", updated.title)
        assertEquals("Hard", updated.difficulty)
        assertEquals("Generated by qwen2.5 as a sliding-window deque problem.", updated.summary)
        assertEquals("Find the maximum in each window.", updated.statementMarkdown)
        assertEquals("nums = [1,3,-1,-3,5,3,6,7]\nk = 3", updated.exampleInput)
        assertEquals("[3,3,5,5,6,7]", updated.exampleOutput)
        assertEquals(ProblemStarterCodeMode.Manual, updated.starterCodeMode)
        assertEquals("Use a deque.", updated.hintsText)
        assertEquals(ProblemExecutionPipeline.SingleMethod.storageValue, updated.executionPipelineOverride)
    }
}
